const fs = require('fs');
const path = require('path');

// Scans public/images/gallery/* and generates src/data/gallery.js
const GALLERY_DIR = path.join(__dirname, '..', 'public', 'images', 'gallery');
const OUT_FILE = path.join(__dirname, '..', 'src', 'data', 'gallery.js');

function captionFromFilename(name) {
  const base = name.replace(/\.[^.]+$/, '');
  const cleaned = base.replace(/[-_]+/g, ' ');
  // Capitalize each word
  return cleaned
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function scan() {
  const categories = fs.readdirSync(GALLERY_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  const items = [];

  categories.forEach(cat => {
    const dir = path.join(GALLERY_DIR, cat);
    const files = fs.readdirSync(dir).filter(f => /\.(jpe?g|png|webp)$/i.test(f));
    files.forEach(f => {
      const src = `/images/gallery/${cat}/${f}`;
      const caption = captionFromFilename(f);
      items.push({ src, caption, category: cat });
    });
  });

  return items;
}

function writeOut(items) {
  const content = `// This file is autogenerated by scripts/generate-gallery.js\n` +
    `// Run: node scripts/generate-gallery.js\n\n` +
    `const gallery = ${JSON.stringify(items, null, 2)};\n\nexport default gallery;\n`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, content, 'utf8');
  console.log('Wrote', OUT_FILE);
}

function main() {
  if (!fs.existsSync(GALLERY_DIR)) {
    console.error('Gallery dir not found:', GALLERY_DIR);
    process.exit(1);
  }
  const items = scan();
  writeOut(items);
}

if (require.main === module) main();
